$image = /ThousanD/XternD/Projects/WallpapersDir/RofiWall/01-Green.jpg

$background = rgba(0f1512ff)

$error = rgba(ffd2ccff)

$error_container = rgba(ff5449ff)

$inverse_on_surface = rgba(252b28ff)

$inverse_primary = rgba(00523fff)

$inverse_surface = rgba(dee4dfff)

$on_background = rgba(dee4dfff)

$on_error = rgba(540003ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(002c20ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(00150eff)

$on_primary_fixed_variant = rgba(003e2fff)

$on_secondary = rgba(132a22ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(00150eff)

$on_secondary_fixed_variant = rgba(243b32ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(d5dfd8ff)

$on_tertiary = rgba(002939ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(00131dff)

$on_tertiary_fixed_variant = rgba(133a4bff)

$outline = rgba(aab4aeff)

$outline_variant = rgba(89938dff)

$primary = rgba(9eecceff)

$primary_container = rgba(539f84ff)

$primary_fixed = rgba(a4f2d4ff)

$primary_fixed_dim = rgba(89d6b9ff)

$scrim = rgba(000000ff)

$secondary = rgba(c8e2d6ff)

$secondary_container = rgba(7d968bff)

$secondary_fixed = rgba(cee9dcff)

$secondary_fixed_dim = rgba(b2ccc0ff)

$shadow = rgba(000000ff)

$source_color = rgba(0f4737ff)

$surface = rgba(0f1512ff)

$surface_bright = rgba(404643ff)

$surface_container = rgba(232926ff)

$surface_container_high = rgba(2e3431ff)

$surface_container_highest = rgba(393f3cff)

$surface_container_low = rgba(191f1cff)

$surface_container_lowest = rgba(040806ff)

$surface_dim = rgba(0f1512ff)

$surface_tint = rgba(89d6b9ff)

$surface_variant = rgba(404944ff)

$tertiary = rgba(bde2f7ff)

$tertiary_container = rgba(7296aaff)

$tertiary_fixed = rgba(c3e8feff)

$tertiary_fixed_dim = rgba(a7cce1ff)

