# ╔══════════════════════════════════════════════════════════════════╗
# ║  ~/.config/hypr/hyprland.conf  — Archivo principal             ║
# ║  Solo carga los módulos. Editá cada archivo por separado.      ║
# ╚══════════════════════════════════════════════════════════════════╝

# ── Colores dinámicos (generado por matugen) ──────────────────────
source = ~/.config/hypr/extra/hyprland-colors.conf

# ── Módulos ───────────────────────────────────────────────────────
source = ~/.config/hypr/Modules/Monitors.conf
source = ~/.config/hypr/Modules/KeybindsAutoS.conf
source = ~/.config/hypr/Modules/Enviromental.conf
source = ~/.config/hypr/Modules/Animations.conf
source = ~/.config/hypr/Modules/Look.conf
source = ~/.config/hypr/Modules/Windowrules.conf


# Smart Gaps - sin gaps cuando hay una sola ventana
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

# Quitar bordes y redondeo cuando está sola (nueva sintaxis V3)
windowrule = match:float false, match:workspace w[tv1], border_size 0
windowrule = match:float false, match:workspace w[tv1], rounding 0
windowrule = match:float false, match:workspace f[1], border_size 0
windowrule = match:float false, match:workspace f[1], rounding 0

