# ╔══════════════════════════════════════════════════════════════════╗
# ║  conf/look.conf                                                 ║
# ╚══════════════════════════════════════════════════════════════════╝
# Refer to https://wiki.hypr.land/Configuring/Variables/

# Source matugen colors — regenerate with matugen and this updates automatically
source = ~/.config/hypr/colors.conf

general {
    gaps_in  = 4
    gaps_out = 3, 9, 9, 9

    border_size         = 2
    col.active_border   = $primary
    col.inactive_border = $outline_variant  # matugen color, cambia con el tema

    resize_on_border = true
    allow_tearing    = true  # lets the `immediate` window rule work

    layout = dwindle  # declarado explícitamente

    snap {
        enabled      = true
        window_gap   = 4
        monitor_gap  = 5
        respect_gaps = true
    }
}

group {
    col.border_active          = $primary
    col.border_inactive        = $outline
    col.border_locked_active   = $error
    col.border_locked_inactive = $outline

    groupbar {
        col.active          = $primary
        col.inactive        = $outline
        col.locked_active   = $error
        col.locked_inactive = $outline
    }
}

dwindle {
    preserve_split = true
}

decoration {
    rounding       = 20
    rounding_power = 2.4

    active_opacity   = 0.93
    inactive_opacity = 0.73  # ventanas inactivas ligeramente transparentes

    blur {
        enabled  = true
        size     = 4      # más natural con menos passes
        passes   = 2      # menos carga en GPU
        xray     = false
        
        ignore_opacity = true
        new_optimizations = true

        popups             = true   # blur en menús y tooltips
        popups_ignorealpha = 0.2
    }

    shadow {
        enabled      = true
        range        = 50
        offset       = 0 4
        render_power = 3            # sombra más suave y realista
        color        = rgba(00000055)  # más visible (33% opacidad)
    }

    dim_inactive = true
    dim_strength = 0.03
}

misc {
    disable_hyprland_logo    = true
    disable_splash_rendering = true
    vrr                      = 1
    mouse_move_enables_dpms  = true
    key_press_enables_dpms   = true
    allow_session_lock_restore = true
    focus_on_activate        = true
    on_focus_under_fullscreen = 2
}
