# ╔══════════════════════════════════════════════════════════════════╗
# ║  conf/windowrules.conf                                          ║
# ║  Sintaxis nueva Hyprland (post windowrulev2 deprecation)        ║
# ║  Ref: https://wiki.hypr.land/Configuring/Window-Rules/         ║
# ╚══════════════════════════════════════════════════════════════════╝

windowrule = no_blur on,no_shadow on, match:class kitty
windowrule = opaque on,no_shadow on, fullscreen_state 3, match:class Minecraft\ 1.12.2
windowrule = opaque on,no_shadow on, match:class waydroid.com.YoStarEN.AzurLane
windowrule = opaque on,no_shadow on, match:class scrcpy
windowrule = opaque on,no_shadow on, match:class steam_proton
windowrule = opaque on,no_shadow on, match:class firefox
windowrule = opaque on,no_shadow on, match:class waterfox
windowrule = opaque on,no_shadow on, match:class mpv
windowrule = opaque on,no_shadow on, match:class Azur\ Lane
windowrule = opaque on,no_shadow on, match:class helium
windowrule = opaque on,no_shadow on, match:class zen

windowrule = opacity 0.80 override 0.80, match:class ^(Alacritty)$
windowrule = opacity 0.80 override 0.80, match:class ^(kitty)$
windowrule = opacity 0.80 override 0.80, match:class ^(thunar)$
windowrule = opacity 0.80 override 0.80, match:class ^(spotify)$
windowrule = opacity 0.80 override 0.80, match:class ^(vesktop)$
windowrule = opacity 0.80 override 0.80, match:class ^(steam)$
windowrule = opacity 0.80 override 0.80, match:class ^(Rofi)$
windowrule = opacity 0.80 override 0.80, match:class ^(swaync)$
windowrule = opacity 0.80 override 0.80, match:class ^(better_control.py)$
